import {useCallback, useState} from "react";
import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import styles from '../styles/Home.module.css';
import { getURL } from "next/dist/next-server/lib/utils";

export default function Home() {

  const [contactList, setContactList] = useState([]);

  const getContact = useCallback( async () => {
    try {
      const response = await axios.get('/api/contacts');
      setContactList(response.data);

    }

    catch(e) {
      console.error(e);
    }

  }, []);

  const newContact = useCallback( async () => {
    try {
      const response = await axios.post('/api/contacts');
      setContactList(response.data);

    }

    catch(e) {
      console.error(e);
    }

  }, []);

  const updateContact = useCallback( async () => {
    try {
      const response = await axios.patch('/api/contacts');
      setContactList(response.data);
    }

    catch(e) {
      console.error(e);
    }

  }, []);

  const removeContact = useCallback( async (id) => {
    try {
      const response = await axios.delete(`/api/contacts/${id}`);
      // setContactList(response.data);
      console.log(response)
    }

    catch(e) {
      console.error(e);
    }

  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>My Contact List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
    <div>
        <h1 className={styles.title}>
          Your contact list!
        </h1>
    </div>

    <div>
      <button onClick={newContact}>New Contact</button>


      <button onClick={getContact}>Get Contacts</button>
      {contactList.map((contact) => (
        <div className={styles.addresslist} key={contact._id}>
         <div className={styles.addresslistitem}> <div className={styles.addresslistimage}> 
         </div> 
         <img className={styles.addresslistimage} src={contact.image} /> {contact.firstName} {contact.lastName} {contact.email} {contact.phone} {contact.work}</div> 
         <button className={styles.addressedit} onClick={updateContact}>Edit</button>
         <button className={styles.addressremove} onClick={() => removeContact(contact._id)}>Remove</button>
        </div>
      ))}
    </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
