import {useCallback, useState} from "react";
import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import ReactDataGrid from 'react-data-grid';
import styles from '../styles/Home.module.css';


export default function Home() {

  const [contactList, setContactList] = useState([]);

  const getContact = useCallback( async () => {
    try {
      const response = await axios.get('/api/contacts');
      setContactList(response.data);

    }

    catch(e) {
      console.error(e);
    }

  }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <button onClick={getContact}>Get Contact</button>
      {contactList.map((contact) => (
        <ul key={contact.id}>
          <li>{contact.firstName}</li>
          <li>{contact.lastName}</li>
          <li>{contact.email}</li>
          <li>{contact.phone}</li>
        </ul>
      ))}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to your Contact List!!
        </h1>
      
        <div class="contactslist"></div>

      
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
